README.md
csv-exporter/pom.xml
csv-exporter/src/main/java/powsybl/tutorials/csv/export/Main.java
csv-importer/pom.xml
csv-importer/src/main/java/powsybl/tutorials/csv/import_/Main.java

* **Please check if the PR fulfills these requirements** (please use `'[x]'` to check the checkboxes, or submit the PR and then click the checkboxes)
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
feature + docs update
* **What is the current behavior?** (You can also link to an open issue here)
one must import the project in an IDE or know how to use maven to launch tutorials
* **What is the new behavior (if this is a feature change)?**
Allow to launch various tutorials with mvn exec:java, for example
```bash
$ mvn package exec:java -pl csv-exporter
```
* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
no

powsybl-tutorials: exec:java and readme

---

README.md

**Please check if the PR fulfills these requirements** 
Small fix in the readme

Tiny Fix README.md

---

loadflow/README.md
loadflow/pom.xml
loadflow/src/main/java/powsybl/tutorials/loadflow/LoadflowTutorial.java
loadflow/src/main/resources/config.yml
loadflow/src/main/resources/eurostag-tutorial1-lf.xml
pom.xml

No.
This PR propose a first version of a tutorial using a loadflow.

First import of loadflow tutorial.

---

cgmes/src/main/java/powsybl/tutorials/cgmes/CgmesMergeTutorial.java
loadflow/pom.xml
pom.xml

Update powsybl dependencies to:
- powsybl-core to 2.5.0
- powsybl-gse to 1.5.0
- powsybl-rte-core to 2.5.0

Update powsybl dependencies

---

cgmes/pom.xml
cgmes/src/main/java/powsybl/tutorials/cgmes/CgmesMergeTutorial.java
loadflow/pom.xml
loadflow/src/main/java/powsybl/tutorials/loadflow/LoadflowTutorial.java
pom.xml

Signed-off-by: Anne Tilloy <atilloy@gmail.com>
(if any of the questions/checkboxes don't apply, please delete them entirely)

Update to powsybl-core 3.0.0

---

cgmes/pom.xml
count-network-lines/pom.xml
csv-exporter/pom.xml
csv-importer/pom.xml
itools-packager/pom.xml
javafx-packager/pom.xml
loadflow/pom.xml
pom.xml

Signed-off-by: RALAMBOTIANA MIORA <miora.ralambotiana@rte-france.com>
Update version
We link each version to a specific powsybl-core release. Since we changed the powsybl-core release core, we should also change the tutorials version.

Prepare release 1.2.0 linked to powsybl-core release 3.1.0

---

loadflow/src/main/java/powsybl/tutorials/loadflow/LoadflowTutorial.java

Give some details about the config, fix minor typos, make some rewording.
Signed-off-by: Agnès Leroy <agnes.leroy@rte-france.com>
**Please check if the PR fulfills these requirements**
- [x ] The commit message follows our guidelines
**Does this PR already have an issue describing the problem ?**
No
Changes in the comments of the loadflow tutorial

Modify the comments in the loadflow tutorial

---

cgmes/pom.xml
count-network-lines/pom.xml
csv-exporter/pom.xml
csv-importer/pom.xml
itools-packager/pom.xml
javafx-packager/pom.xml
loadflow/pom.xml
pom.xml
sensitivity/pom.xml
topology/pom.xml

Prepare next version 1.3.0 compatible with powsybl-core 3.2.0 and powsybl-rte-core 2.9.0

Prepare next version 1.3.0

---

pom.xml
topology/src/main/java/powsybl/tutorials/topology/VoltageLevelTopologyTutorial.java

N/A
Dependency update
The project use powsybl-core v3.2.0 and powsybl-rte-core v2.9.0
The project use powsybl-core v3.3.0 and powsybl-rte-core v2.10.0
(if any of the …

Update dependency versions

---

loadflow/complete/pom.xml
loadflow/initial/pom.xml
pom.xml
sensitivity/complete/pom.xml
sensitivity/complete/src/main/java/powsybl/tutorials/sensitivity/SensitivityTutorialComplete.java
sensitivity/complete/src/main/resources/config.yml
sensitivity/initial/pom.xml

Adapt tutorial code to sensi API refactoring

Adapt sensitivity tutorial after sensi API refactoring

---

.github/workflows/maven.yml
pom.xml

N/A
Dependency update
The current version of logback is v1.1.8. This version contains vulnerabilities:
https://app.snyk.io/vuln/SNYK-JAVA-CHQOSLOGBACK-31407
https://app.snyk.io/vuln/SNYK-JAVA-CHQOSLOGBACK-30208
Try to update the version to fix the vulnerabilities and check powsybl security report …

Update logback version to v1.2.3

---

README.md
cgmes/README.md
loadflow/README.md
sensitivity/README.md
topology/README.md

N/A
Dead links
The readme page contains obsolete information and dead links
LInks have been updated and obsolete information have been removed or updated
(if any of the …

Fix dead links

---

loadflow/README.md
loadflow/complete/pom.xml
loadflow/complete/src/main/java/powsybl/tutorials/loadflow/LoadflowTutorialComplete.java
loadflow/complete/src/main/resources/config.yml

(if any of the questions/checkboxes don't apply, please delete them entirely)

Openloadflow tutorial update

---

loadflow/initial/src/main/java/powsybl/tutorials/loadflow/LoadFlowTutorial.java
sensitivity/initial/src/main/java/powsybl/tutorials/sensitivity/SensitivityTutorial.java
topology/src/main/java/powsybl/tutorials/topology/VoltageLevelTopologyTutorial.java

Yes, after LFE licence scanning: https://lfscanning.org/reports/lfenergy/powsybl-2021-04-20-ed46eeb7-b4a3-4f66-8266-e757e3fb0c46.xlsx
(if any of the questions/checkboxes don't …

Fix: license header

---

downscaling/README.md

(if any of the questions/checkboxes don't apply, please delete them entirely)

Fix README.md

---

cgmes/src/main/java/powsybl/tutorials/cgmes/CgmesMergeTutorial.java
emf/README.md
emf/pom.xml
pom.xml

Signed-off-by: Coline Piloquet <coline.piloquet@rte-france.com>
No
The versions of powsybl-balances-adjustment and powsybl-entsoe are updated in the Emf tutorial to support scaling with constant power factor. The readme is updated with link to the website documentation

Update versions of dependencies in Emf tutorial

---

emf/pom.xml
loadflow/initial/pom.xml
pom.xml
sensitivity/complete/pom.xml
sensitivity/initial/pom.xml

N/A
Dependency fix
The base `pom.xml` provided in some tutorials is not compatible with the code we expect to be written following the tutorials of the website.
The pom.xml have been fixed. I also fixed the version of logback-classic because the version used contains a critical vulnerability. …

Fix powsybl version

---

pom.xml
sld-custom-node/pom.xml
sld-custom-node/src/main/java/com/powsybl/tutorials/sld/customnode/SldCustomNodeTutorial.java
sld-custom-node/src/main/resources/CustomLibrary/components.css
sld-custom-node/src/main/resources/CustomLibrary/components.json
sld-custom-node/src/main/resources/CustomLibrary/wind-turbine.svg

**Please check if the PR fulfills these requirements**
**Does this PR already have an issue describing the problem ?**
No
New tutorial for adding custom feeder node with custom component icon in powsybl-single-line-diagram

SLD custom node tutorial

---

cgmes/src/main/java/com/powsybl/tutorials/cgmes/CgmesMergeTutorial.java
count-network-lines/pom.xml
count-network-lines/src/main/java/com/powsybl/tutorials/tools/CountNetworkLinesTool.java
csv-exporter/pom.xml
csv-exporter/src/main/java/com/powsybl/tutorials/csv/export/CsvLinesExporter.java
csv-exporter/src/main/java/com/powsybl/tutorials/csv/export/Main.java
csv-importer/pom.xml
csv-importer/src/main/java/com/powsybl/tutorials/csv/import_/CsvLinesImporter.java
csv-importer/src/main/java/com/powsybl/tutorials/csv/import_/Main.java
emf/pom.xml
emf/src/main/java/com/powsybl/tutorials/emf/EmfTutorial.java
loadflow/src/main/java/com/powsybl/tutorials/loadflow/LoadflowTutorial.java
merging-view/src/main/java/com/powsybl/tutorials/mergingview/MergingViewTutorial.java
pom.xml
sensitivity/src/main/java/com/powsybl/tutorials/sensitivity/SensitivityTutorial.java
sld-custom-node/src/main/java/com/powsybl/tutorials/sld/customnode/SldCustomNodeTutorial.java

Feature
Tutorials were based on core 4.9.1 (through dependencies 1.2.1).
Tutorials based on core 5.0.0 (through dependencies 1.4.0).

Update to PowSyBl dependencies 2022.0.2

---

downscaling/complete/pom.xml
downscaling/complete/src/main/java/com/powsybl/tutorials/downscaling/Downscaling.java
pom.xml
sld-custom-node/src/main/java/com/powsybl/tutorials/sld/customnode/SldCustomNodeTutorial.java

Keep tutorials up-to-date and functional following powsybl-core 5.1.1 release

Update tutorials for 511

---

cgmes/src/main/java/com/powsybl/tutorials/cgmes/CgmesMergeTutorial.java
emf/pom.xml
emf/src/main/java/com/powsybl/tutorials/emf/BalancesAdjustmentValidationParameters.java
merging/pom.xml
pom.xml

**Please check if the PR fulfills these requirements**
**Does this PR already have an issue describing the problem?**
No
Dependencies version update
**What is the current behavior?**
powsybl-dependencies version is set to 2023.3.1.
powsybl-dependencies version is set to 2024.2.0 and code is updated where it should be.
**Does this PR introduce a breaking change or deprecate an API?**

Update to powsybl-dependencies 2024.2.0
